package net.avatarapps.dopa.dashboard.dashboard.view.zones.areas

data class State(
        val id: Int,
        val nameAr: String,
        val nameEn: String,
        val districts: ArrayList<District>
)

data class District(
        val id: Int,
        val nameAr: String,
        val nameEn: String,
        val neighbourhoods: ArrayList<Neighbourhood>
)

data class Neighbourhood(
        val id: Int,
        val nameAr: String,
        val nameEn: String
)


object Areas {
//    val states = arrayListOf(
//            State(1, "الخرطوم", "Khartoum", arrayListOf(
//                    District(1, "بحري", "Bahri", arrayListOf(
//                            Neighbourhood(1, "شمبات جنوب", "South Shambat"),
//                            Neighbourhood(2, "الدروشاب", "Aldroushab"),
//                            Neighbourhood(3, "الصبابي", "Alsababi"),
//                            Neighbourhood(4, "كافوري", "Kafouri"),
//                            Neighbourhood(5, "الكدرو", "Alkadaro")
//                    )
//                    )
//            )
//            )
//    )

    val states = arrayListOf(
            State(1, "الخرطوم", "Khartoum", arrayListOf(
                    District(1, "كرري", "كرري", arrayListOf(
                            Neighbourhood(1, " الاحامدة مبروكة", " الاحامدة مبروكة"),
                            Neighbourhood(15, "ابو سنقد", ""),
                            Neighbourhood(16, "ابو شمبلة", ""),
                            Neighbourhood(20, "ابو فاس", ""),
                            Neighbourhood(27, "ابو مريخ", ""),
                            Neighbourhood(52, "الاحامدة الجادلاب", ""),
                            Neighbourhood(79, "الاسكان", ""),
                            Neighbourhood(86, "الامتاب و الاحامدة", ""),
                            Neighbourhood(115, "البادوية البير", ""),
                            Neighbourhood(119, "البحيراب و القلعة الطيبة", ""),
                            Neighbourhood(126, "البرياب والصلحاب", ""),
                            Neighbourhood(134, "البير", ""),
                            Neighbourhood(143, "التسعين", ""),
                            Neighbourhood(156, "الجابراب و البرارة", ""),
                            Neighbourhood(165, "الجرافة", ""),
                            Neighbourhood(178, "الجزيرة اسلانج شرق", ""),
                            Neighbourhood(179, "الجزيرة اسلانج شمال غرب", ""),
                            Neighbourhood(183, "الجموعية و بلول", ""),
                            Neighbourhood(194, "كرري الحارة 17", ""),
                            Neighbourhood(195, "كرري الحارة 18", ""),
                            Neighbourhood(196, "كرري الحارة 19", ""),
                            Neighbourhood(197, "كرري الحارة 20", ""),
                            Neighbourhood(198, "كرري الحارة 21", ""),
                            Neighbourhood(199, "كرري الحارة 30", ""),
                            Neighbourhood(200, "كرري الحارة 31", ""),
                            Neighbourhood(201, "كرري الحارة 34", ""),
                            Neighbourhood(202, "كرري الحارة 35", ""),
                            Neighbourhood(203, "كرري الحارة 36", ""),
                            Neighbourhood(204, "كرري الحارة 37", ""),
                            Neighbourhood(205, "كرري الحارة 38", ""),
                            Neighbourhood(206, "كرري الحارة 39", ""),
                            Neighbourhood(207, "كرري الحارة 40", ""),
                            Neighbourhood(208, "كرري الحارة 41-أ", ""),
                            Neighbourhood(209, "كرري الحارة 41-ب", ""),
                            Neighbourhood(210, "كرري الحارة 42", ""),
                            Neighbourhood(211, "كرري الحارة 43", ""),
                            Neighbourhood(212, "كرري الحارة 44", ""),
                            Neighbourhood(213, "كرري الحارة 45", ""),
                            Neighbourhood(214, "كرري الحارة 46", ""),
                            Neighbourhood(215, "كرري الحارة 47", ""),
                            Neighbourhood(217, "كرري الحارة 48", ""),
                            Neighbourhood(218, "كرري الحارة 49", ""),
                            Neighbourhood(219, "كرري الحارة 52", ""),
                            Neighbourhood(220, "كرري الحارة 53", ""),
                            Neighbourhood(221, "كرري الحارة 54", ""),
                            Neighbourhood(222, "كرري الحارة 55", ""),
                            Neighbourhood(223, "كرري الحارة 56", ""),
                            Neighbourhood(224, "كرري الحارة 57", ""),
                            Neighbourhood(225, "كرري الحارة 59 جنوب", ""),
                            Neighbourhood(226, "كرري الحارة 59 شمال", ""),
                            Neighbourhood(227, "كرري الحارة 60 شرق", ""),
                            Neighbourhood(228, "كرري الحارة 60 غرب", ""),
                            Neighbourhood(229, "كرري الحارة 61", ""),
                            Neighbourhood(230, "كرري الحارة 63", ""),
                            Neighbourhood(231, "كرري الحارة 65", ""),
                            Neighbourhood(232, "كرري الحارة 71", ""),
                            Neighbourhood(233, "كرري الحارة 72", ""),
                            Neighbourhood(234, "كرري الحارة 73", ""),
                            Neighbourhood(236, "الثورات الحارة1", ""),
                            Neighbourhood(238, "الثورات الحارة10", ""),
                            Neighbourhood(240, "الثورات الحارة11", ""),
                            Neighbourhood(242, "الثورات الحارة12", ""),
                            Neighbourhood(243, "الثورات الحارة13", ""),
                            Neighbourhood(245, "الثورات الحارة14", ""),
                            Neighbourhood(256, "الثورات الحارة15", ""),
                            Neighbourhood(260, "الثورات الحارة16", ""),
                            Neighbourhood(270, "الثورات الحارة2", ""),
                            Neighbourhood(274, "الثورات الحارة22", ""),
                            Neighbourhood(276, "الثورات الحارة23", ""),
                            Neighbourhood(278, "الثورات الحارة24", ""),
                            Neighbourhood(280, "الثورات الحارة25", ""),
                            Neighbourhood(282, "الثورات الحارة26", ""),
                            Neighbourhood(284, "الثورات الحارة27", ""),
                            Neighbourhood(286, "الثورات الحارة28", ""),
                            Neighbourhood(288, "الثورات الحارة29 جنوب", ""),
                            Neighbourhood(289, "الثورات الحارة29 شمال", ""),
                            Neighbourhood(291, "الثورات الحارة3", ""),
                            Neighbourhood(303, "الثورات الحارة4", ""),
                            Neighbourhood(313, "الثورات الحارة5", ""),
                            Neighbourhood(314, "الثورات الحارة50", ""),
                            Neighbourhood(315, "الثورات الحارة51", ""),
                            Neighbourhood(318, "الثورات الحارة58", ""),
                            Neighbourhood(319, "الثورات الحارة6", ""),
                            Neighbourhood(322, "الثورات الحارة62", ""),
                            Neighbourhood(323, "الثورات الحارة7", ""),
                            Neighbourhood(326, "الثورات الحارة8", ""),
                            Neighbourhood(329, "الثورات الحارة9", ""),
                            Neighbourhood(332, "الحتانة جنوب", ""),
                            Neighbourhood(333, "الحتانة شمال", ""),
                            Neighbourhood(334, "الحتانة مربع 10", ""),
                            Neighbourhood(335, "الحجير ام دوم", ""),
                            Neighbourhood(339, "الحريزاب", ""),
                            Neighbourhood(350, "الحقيبة", ""),
                            Neighbourhood(375, "الحوشاب", ""),
                            Neighbourhood(379, "الخدير", ""),
                            Neighbourhood(409, "الدشيناب الام", ""),
                            Neighbourhood(410, "الدشيناب شمال", ""),
                            Neighbourhood(414, "الدليلاب الزهور الحقيبة", ""),
                            Neighbourhood(430, "الرشاد", ""),
                            Neighbourhood(436, "الروضة", ""),
                            Neighbourhood(437, "الروضة الحسانية", ""),
                            Neighbourhood(439, "الرياض", ""),
                            Neighbourhood(464, "السروراب جنوب", ""),
                            Neighbourhood(465, "السروراب شمال", ""),
                            Neighbourhood(466, "السروراب وسط", ""),
                            Neighbourhood(469, "السعدية", ""),
                            Neighbourhood(475, "السكن الفاخر", ""),
                            Neighbourhood(496, "السناهير", ""),
                            Neighbourhood(498, "الشاطئ جنوب", ""),
                            Neighbourhood(499, "الشاطئ شمال", ""),
                            Neighbourhood(501, "الشبراب جنوب جاداب", ""),
                            Neighbourhood(502, "الشبراب شمال والريداب الحمراب", ""),
                            Neighbourhood(513, "الشقايق", ""),
                            Neighbourhood(532, "الشهيناب جنوب", ""),
                            Neighbourhood(533, "الشهيناب شمال", ""),
                            Neighbourhood(537, "الشيخ الطيب شمال", ""),
                            Neighbourhood(538, "الشيخ الطيب وسط جنوب", ""),
                            Neighbourhood(564, "الصلحاب", ""),
                            Neighbourhood(567, "الضريواب", ""),
                            Neighbourhood(571, "الطويل", ""),
                            Neighbourhood(617, "الفادنية", ""),
                            Neighbourhood(623, "الفتج 2- الفاروق", ""),
                            Neighbourhood(624, "الفتح 1- اباذر العقاب", ""),
                            Neighbourhood(625, "الفتح 1- ابوبكر الصديق", ""),
                            Neighbourhood(626, "الفتح 1- خالد بن الوليد", ""),
                            Neighbourhood(627, "الفتح 1- مصعب بن عمير", ""),
                            Neighbourhood(628, "الفتح 1- معاذ بن جبل", ""),
                            Neighbourhood(629, "الفتح 2- التقوى", ""),
                            Neighbourhood(630, "الفتح 2- السلام", ""),
                            Neighbourhood(631, "الفتح 2- الوحدة", ""),
                            Neighbourhood(632, "الفتح 2 - الطائف", ""),
                            Neighbourhood(634, "الفردوس", ""),
                            Neighbourhood(664, "القدوراب الجعليين", ""),
                            Neighbourhood(675, "القلعة العمرية", ""),
                            Neighbourhood(681, "القلعية الحارة 32", ""),
                            Neighbourhood(684, "القليعة الحارة 33", ""),
                            Neighbourhood(699, "الكبابيش غرب", ""),
                            Neighbourhood(706, "الكرانك ود عمر", ""),
                            Neighbourhood(718, "الكواهلة", ""),
                            Neighbourhood(719, "الكوداب", ""),
                            Neighbourhood(752, "المكاوير", ""),
                            Neighbourhood(756, "المنارة الاحامدة", ""),
                            Neighbourhood(790, "النوبة", ""),
                            Neighbourhood(792, "النوفلاب", ""),
                            Neighbourhood(799, "الهواوير", ""),
                            Neighbourhood(802, "الواحة شرق", ""),
                            Neighbourhood(803, "الواحة غرب", ""),
                            Neighbourhood(804, "الوادى الابيض", ""),
                            Neighbourhood(805, "الوادى الاخضر جنوب", ""),
                            Neighbourhood(806, "الوادى الاخضر شمال", ""),
                            Neighbourhood(808, "الوحدة الاحامدة", ""),
                            Neighbourhood(860, "ام غريز", ""),
                            Neighbourhood(863, "ام كتى", ""),
                            Neighbourhood(885, "اولاد الهادي", ""),
                            Neighbourhood(910, "بلال", ""),
                            Neighbourhood(911, "بياع القريات", ""),
                            Neighbourhood(967, "خور عمر", ""),
                            Neighbourhood(1012, "شرفت العبدلاب والتميراب", ""),
                            Neighbourhood(1013, "شرفت الفقيراب", ""),
                            Neighbourhood(1028, "طيبة الحسانية", ""),
                            Neighbourhood(1032, "عد الحجر و الرحل", ""),
                            Neighbourhood(1086, "قوز نفيسة", ""),
                            Neighbourhood(1092, "كررى العجيجة", ""),
                            Neighbourhood(1115, "مدينة النيل", ""),
                            Neighbourhood(1221, "ميدان 27 اباذر العقاب", ""),
                            Neighbourhood(1233, "ود البخيت", ""),
                            Neighbourhood(1236, "ود الحوري", ""),
                            Neighbourhood(1242, "ود حنيو", "")
                    )),
                    District(2, "امدرمان", "", arrayListOf(
                            Neighbourhood(2, " الجامراب ود النور", ""),
                            Neighbourhood(19, "ابو عنجة", ""),
                            Neighbourhood(26, "ابو كدوك", ""),
                            Neighbourhood(28, "ابو هشيم العجيماب", ""),
                            Neighbourhood(29, "ابو هشيم الكبابيش", ""),
                            Neighbourhood(30, "ابوروف جنوب", ""),
                            Neighbourhood(31, "ابوروف شمال", ""),
                            Neighbourhood(32, "ابوروف والهجرة", ""),
                            Neighbourhood(33, "ابوروف وسط", ""),
                            Neighbourhood(36, "ابوضغينة", ""),
                            Neighbourhood(78, "الاسبتالية", ""),
                            Neighbourhood(95, "الامراء", ""),
                            Neighbourhood(131, "البوستة جنوب", ""),
                            Neighbourhood(132, "البوستة شمال", ""),
                            Neighbourhood(139, "التريس", ""),
                            Neighbourhood(149, "التكامل", ""),
                            Neighbourhood(157, "الجامراب البادراب", ""),
                            Neighbourhood(158, "الجامراب الجادالاب", ""),
                            Neighbourhood(159, "الجامراب الضهير", ""),
                            Neighbourhood(160, "الجامراب ود الامين", ""),
                            Neighbourhood(161, "الجامراب ود الجاك", ""),
                            Neighbourhood(162, "الجامراب ود محمود", ""),
                            Neighbourhood(193, "الحاجاب", ""),
                            Neighbourhood(349, "الحفير", ""),
                            Neighbourhood(351, "الحقينة", ""),
                            Neighbourhood(393, "الدباغة", ""),
                            Neighbourhood(418, "الدواليب", ""),
                            Neighbourhood(419, "الدوحة", ""),
                            Neighbourhood(432, "الركابية", ""),
                            Neighbourhood(488, "السليمانية", ""),
                            Neighbourhood(493, "السمرة والطلحة", ""),
                            Neighbourhood(503, "الشبيلاب", ""),
                            Neighbourhood(507, "الشرفية", ""),
                            Neighbourhood(516, "الشقلة شرق", ""),
                            Neighbourhood(518, "الشقلة وسط", ""),
                            Neighbourhood(525, "الشقيلة", ""),
                            Neighbourhood(529, "الشهداء جنوب", ""),
                            Neighbourhood(530, "الشهداء شمال", ""),
                            Neighbourhood(534, "الشيخ احمد بدر", ""),
                            Neighbourhood(536, "الشيخ البشير", ""),
                            Neighbourhood(560, "الصفا", ""),
                            Neighbourhood(565, "الصندوداب", ""),
                            Neighbourhood(573, "العامرة", ""),
                            Neighbourhood(574, "العباسية الام", ""),
                            Neighbourhood(575, "العباسية جنوب", ""),
                            Neighbourhood(576, "العباسية شرق", ""),
                            Neighbourhood(577, "العباسية شمال", ""),
                            Neighbourhood(578, "العباسية غرب", ""),
                            Neighbourhood(579, "العباسية وسط", ""),
                            Neighbourhood(582, "العرضة جنوب", ""),
                            Neighbourhood(583, "العرضة شمال", ""),
                            Neighbourhood(584, "العرضة وسط", ""),
                            Neighbourhood(593, "العشرة", ""),
                            Neighbourhood(599, "العقيدات", ""),
                            Neighbourhood(604, "العمدة جنوب", ""),
                            Neighbourhood(605, "العمدة شرق", ""),
                            Neighbourhood(606, "العمدة شمال", ""),
                            Neighbourhood(607, "العمدة غرب", ""),
                            Neighbourhood(608, "العيساوية غرب", ""),
                            Neighbourhood(612, "الغرزة", ""),
                            Neighbourhood(613, "الغماراب", ""),
                            Neighbourhood(649, "الفكي علي", ""),
                            Neighbourhood(674, "القلعة", ""),
                            Neighbourhood(682, "القليع", ""),
                            Neighbourhood(683, "القليعة", ""),
                            Neighbourhood(685, "القماير", ""),
                            Neighbourhood(696, "القيعة", ""),
                            Neighbourhood(701, "الكبجاب", ""),
                            Neighbourhood(715, "الكموناب", ""),
                            Neighbourhood(721, "الكوع", ""),
                            Neighbourhood(739, "المسالمة شرق", ""),
                            Neighbourhood(740, "المسالمة غرب", ""),
                            Neighbourhood(742, "المصاحة", ""),
                            Neighbourhood(743, "المظاهر", ""),
                            Neighbourhood(749, "المقداب", ""),
                            Neighbourhood(753, "الملازمين شرق", ""),
                            Neighbourhood(754, "الملازمين غرب", ""),
                            Neighbourhood(764, "المنطقة الصناعية", ""),
                            Neighbourhood(767, "المهندسين م28", ""),
                            Neighbourhood(768, "المهندسين م29", ""),
                            Neighbourhood(769, "المهندسين م30", ""),
                            Neighbourhood(771, "الموردة جنوب", ""),
                            Neighbourhood(772, "الموردة شرق", ""),
                            Neighbourhood(773, "الموردة غرب", ""),
                            Neighbourhood(774, "الموردة وسط", ""),
                            Neighbourhood(775, "المويلح", ""),
                            Neighbourhood(794, "الهاشماب", ""),
                            Neighbourhood(796, "الهدى", ""),
                            Neighbourhood(818, "الودي", ""),
                            Neighbourhood(822, "ام القرى", ""),
                            Neighbourhood(840, "ام سرحة", ""),
                            Neighbourhood(859, "ام عوينة", ""),
                            Neighbourhood(865, "ام مويخة", ""),
                            Neighbourhood(872, "امتداد بيت المال أ", ""),
                            Neighbourhood(873, "امتداد بيت المال جنوب", ""),
                            Neighbourhood(881, "اولاد اسماعيل", ""),
                            Neighbourhood(889, "ايد ابوزيد", ""),
                            Neighbourhood(890, "ايد الحد", ""),
                            Neighbourhood(891, "ايد ود دياب", ""),
                            Neighbourhood(893, "باروكة", ""),
                            Neighbourhood(895, "بانت شرق", ""),
                            Neighbourhood(896, "بانت غرب", ""),
                            Neighbourhood(897, "بانت وسط", ""),
                            Neighbourhood(902, "بركة الشاطئ", ""),
                            Neighbourhood(903, "بركة الغربية", ""),
                            Neighbourhood(912, "بيت المال شرق", ""),
                            Neighbourhood(913, "بيت المال شمال", ""),
                            Neighbourhood(914, "بيت المال غرب", ""),
                            Neighbourhood(923, "جادين", ""),
                            Neighbourhood(931, "جبيل الطينة", ""),
                            Neighbourhood(942, "حى السيد المكى", ""),
                            Neighbourhood(954, "حي الصفا", ""),
                            Neighbourhood(955, "حي الضباط", ""),
                            Neighbourhood(956, "حي العرب شرق", ""),
                            Neighbourhood(957, "حي العرب غرب", ""),
                            Neighbourhood(988, "سريحة مربع19", ""),
                            Neighbourhood(989, "سريحة مربع5", ""),
                            Neighbourhood(1011, "شرفت", ""),
                            Neighbourhood(1020, "صالحة شرق", ""),
                            Neighbourhood(1021, "صريو", ""),
                            Neighbourhood(1055, "عمورات", ""),
                            Neighbourhood(1056, "عويضة", ""),
                            Neighbourhood(1060, "فتاشة", ""),
                            Neighbourhood(1081, "قلعة دحلوب", ""),
                            Neighbourhood(1082, "قلعة محينة", ""),
                            Neighbourhood(1085, "قوز النصير", ""),
                            Neighbourhood(1090, "كدي جنوب", ""),
                            Neighbourhood(1091, "كدي شمال", ""),
                            Neighbourhood(1100, "كمبو سامي", ""),
                            Neighbourhood(1101, "كمبو مساعد", ""),
                            Neighbourhood(1116, "ابو سعد مربع1", ""),
                            Neighbourhood(1117, "الفتيحاب مربع1", ""),
                            Neighbourhood(1119, "ابو سعد مربع10", ""),
                            Neighbourhood(1121, "ابو سعد مربع11", ""),
                            Neighbourhood(1123, "الفتيحاب مربع12", ""),
                            Neighbourhood(1125, "ابو سعد مربع13", ""),
                            Neighbourhood(1127, "ابو سعد مربع14", ""),
                            Neighbourhood(1129, "ابو سعد مربع15", ""),
                            Neighbourhood(1131, "ابو سعد مربع16", ""),
                            Neighbourhood(1133, "ابو سعد مربع17", ""),
                            Neighbourhood(1135, "ابو سعد مربع18", ""),
                            Neighbourhood(1137, "ابو سعد مربع19", ""),
                            Neighbourhood(1140, "ابو سعد مربع2 جنوب", ""),
                            Neighbourhood(1141, "الفتيحاب مربع2 جنوب", ""),
                            Neighbourhood(1142, "ابو سعد مربع2 شمال", ""),
                            Neighbourhood(1143, "الفتيحاب مربع2 شمال", ""),
                            Neighbourhood(1144, "ابو سعد مربع20", ""),
                            Neighbourhood(1146, "ابو سعد مربع21", ""),
                            Neighbourhood(1148, "ابو سعد مربع22", ""),
                            Neighbourhood(1150, "ابو سعد مربع23", ""),
                            Neighbourhood(1152, "ابو سعد مربع24", ""),
                            Neighbourhood(1154, "ابو سعد مربع24 اسكان الشرطة", ""),
                            Neighbourhood(1155, "ابو سعد مربع25", ""),
                            Neighbourhood(1157, "ابو سعد مربع26", ""),
                            Neighbourhood(1159, "ابو سعد مربع27", ""),
                            Neighbourhood(1161, "ابو سعد مربع28", ""),
                            Neighbourhood(1163, "ابو سعد مربع29", ""),
                            Neighbourhood(1165, "ابو سعد مربع3", ""),
                            Neighbourhood(1166, "الفتيحاب مربع3", ""),
                            Neighbourhood(1172, "ابو سعد مربع33-34", ""),
                            Neighbourhood(1176, "ابو سعد مربع37", ""),
                            Neighbourhood(1179, "ابو سعد مربع4", ""),
                            Neighbourhood(1181, "الفتيحاب مربع4 جنوب", ""),
                            Neighbourhood(1182, "الفتيحاب مربع4 شمال", ""),
                            Neighbourhood(1183, "ابو سعد مربع40", ""),
                            Neighbourhood(1187, "ابو سعد مربع43", ""),
                            Neighbourhood(1189, "ابو سعد مربع44", ""),
                            Neighbourhood(1191, "ابو سعد مربع45", ""),
                            Neighbourhood(1193, "ابو سعد مربع46", ""),
                            Neighbourhood(1195, "ابو سعد مربع47", ""),
                            Neighbourhood(1197, "ابو سعد مربع48", ""),
                            Neighbourhood(1199, "ابو سعد مربع49", ""),
                            Neighbourhood(1201, "ابو سعد مربع5", ""),
                            Neighbourhood(1203, "ابو سعد مربع50", ""),
                            Neighbourhood(1205, "ابو سعد مربع55", ""),
                            Neighbourhood(1206, "ابو سعد مربع56", ""),
                            Neighbourhood(1207, "ابو سعد مربع58", ""),
                            Neighbourhood(1208, "الفتيحاب مربع6", ""),
                            Neighbourhood(1210, "ابو سعد مربع60", ""),
                            Neighbourhood(1211, "الفتيحاب مربع7", ""),
                            Neighbourhood(1213, "ابو سعد مربع8", ""),
                            Neighbourhood(1215, "ابو سعد مربع9", ""),
                            Neighbourhood(1217, "ابو سعد مريع62 اللاسلكي", ""),
                            Neighbourhood(1223, "هجيليجة", ""),
                            Neighbourhood(1225, "وادي الحمرة", ""),
                            Neighbourhood(1235, "ود البنا", ""),
                            Neighbourhood(1257, "ود نوباوي جنوب", ""),
                            Neighbourhood(1258, "ود نوباوي شمال", ""),
                            Neighbourhood(1259, "ود نوباوي وسط", "")
                    )),
                    District(3, "الخرطوم", "", arrayListOf(
                            Neighbourhood(3, " الحلة الجديدة شمال أ", ""),
                            Neighbourhood(5, " الشهيد طه الماحي", ""),
                            Neighbourhood(39, "اركويت مربع 59", ""),
                            Neighbourhood(40, "اركويت مربع43-46", ""),
                            Neighbourhood(41, "اركويت مربع44-45", ""),
                            Neighbourhood(42, "اركويت مربع47-49", ""),
                            Neighbourhood(43, "اركويت مربع48", ""),
                            Neighbourhood(44, "اركويت مربع50-55", ""),
                            Neighbourhood(45, "اركويت مربع50 الاستثماري-54", ""),
                            Neighbourhood(46, "اركويت مربع56", ""),
                            Neighbourhood(47, "اركويت مربع61", ""),
                            Neighbourhood(48, "اركويت مربع62-63", ""),
                            Neighbourhood(49, "اركويت مربع65", ""),
                            Neighbourhood(50, "اركويت مربع68", ""),
                            Neighbourhood(82, "الاشلاق", ""),
                            Neighbourhood(91, "الامتداد م1-2-3-4", ""),
                            Neighbourhood(92, "الامتداد م13-14", ""),
                            Neighbourhood(93, "الامتداد م5-6-9-10", ""),
                            Neighbourhood(94, "الامتداد م7-11-12", ""),
                            Neighbourhood(144, "التعايشة شرق", ""),
                            Neighbourhood(145, "التعايشة غرب", ""),
                            Neighbourhood(171, "الجريف غرب الحارة1 أ-ب", ""),
                            Neighbourhood(172, "الجريف غرب الحارة1ج والاصلاحية", ""),
                            Neighbourhood(173, "الجريف غرب الحارة2", ""),
                            Neighbourhood(174, "الجريف غرب الحارة3", ""),
                            Neighbourhood(175, "الجريف غرب الحارة4", ""),
                            Neighbourhood(176, "الجريف غرب الحارة5", ""),
                            Neighbourhood(177, "الجريف غرب الحارة6", ""),
                            Neighbourhood(186, "الجوامعة", ""),
                            Neighbourhood(353, "الحلة الجديدة جنوب شرق", ""),
                            Neighbourhood(354, "الحلة الجديدة جنوب غرب", ""),
                            Neighbourhood(356, "الحلة الجديدة شمال ب", ""),
                            Neighbourhood(359, "الحلة الجديدة وسط 1", ""),
                            Neighbourhood(360, "الحلة الجديدة وسط 2", ""),
                            Neighbourhood(371, "الحماداب شمال", ""),
                            Neighbourhood(372, "الحمادداب جنوب", ""),
                            Neighbourhood(380, "الخرطوم 1,2", ""),
                            Neighbourhood(381, "الخرطوم 3", ""),
                            Neighbourhood(382, "الخرطوم 3 شرق", ""),
                            Neighbourhood(383, "الخرطوم 3 شمال", ""),
                            Neighbourhood(384, "الخرطوم جنوب", ""),
                            Neighbourhood(391, "الدباسين شرق", ""),
                            Neighbourhood(392, "الدباسين غرب", ""),
                            Neighbourhood(425, "الديم وسط شرق مربع 1", ""),
                            Neighbourhood(426, "الديم وسط شرق مربع 2", ""),
                            Neighbourhood(427, "الديم وسط غرب أ", ""),
                            Neighbourhood(428, "الديم وسط غرب ب", ""),
                            Neighbourhood(433, "الرميلة جنوب مربع 1", ""),
                            Neighbourhood(434, "الرميلة جنوب مربع 2", ""),
                            Neighbourhood(435, "الرميلة شمال مربع 3-4", ""),
                            Neighbourhood(440, "الرياض جنوب", ""),
                            Neighbourhood(441, "الرياض شرق  مربعات 9-11-12", ""),
                            Neighbourhood(442, "الرياض غرب مربع 7-8-10", ""),
                            Neighbourhood(443, "الرياض وسط مربعات 13-14-15-16", ""),
                            Neighbourhood(457, "السباق شرق", ""),
                            Neighbourhood(458, "السباق غرب", ""),
                            Neighbourhood(459, "السجانة الجديدة شرق", ""),
                            Neighbourhood(460, "السجانة الجديدة غرب", ""),
                            Neighbourhood(461, "السجانة شرق", ""),
                            Neighbourhood(462, "السجانة غرب", ""),
                            Neighbourhood(497, "السوق المركزي", ""),
                            Neighbourhood(504, "الشجرة جنوب", ""),
                            Neighbourhood(505, "الشجرة شمال", ""),
                            Neighbourhood(531, "الشهيد الزبير", ""),
                            Neighbourhood(548, "الصحافة  جنوب م23-24", ""),
                            Neighbourhood(549, "الصحافة  شرق م37-40", ""),
                            Neighbourhood(550, "الصحافة  غرب م16-17", ""),
                            Neighbourhood(551, "الصحافة  وسط م29-31", ""),
                            Neighbourhood(552, "الصحافة جنوب  م22-25", ""),
                            Neighbourhood(553, "الصحافة جنوب  م27-28", ""),
                            Neighbourhood(554, "الصحافة شرق م41-42", ""),
                            Neighbourhood(555, "الصحافة غرب  م20-21", ""),
                            Neighbourhood(556, "الصحافة غرب م15-18", ""),
                            Neighbourhood(557, "الصحافة م36-38", ""),
                            Neighbourhood(558, "الصحافة وسط 34-35", ""),
                            Neighbourhood(559, "الصحافة وسط م30-33", ""),
                            Neighbourhood(568, "الطائف جنوب", ""),
                            Neighbourhood(569, "الطائف شمال", ""),
                            Neighbourhood(589, "العزوزاب مربع1", ""),
                            Neighbourhood(590, "العزوزاب مربع2-3", ""),
                            Neighbourhood(594, "العشرة م1-2-3-4", ""),
                            Neighbourhood(595, "العشرة م5-6-78", ""),
                            Neighbourhood(596, "العشرة م9-10-11", ""),
                            Neighbourhood(602, "العمارات جنوب", ""),
                            Neighbourhood(603, "العمارات شمال", ""),
                            Neighbourhood(635, "الفردوس جنوب", ""),
                            Neighbourhood(636, "الفردوس شمال", ""),
                            Neighbourhood(637, "الفردوس مربع81", ""),
                            Neighbourhood(638, "الفردوس والمزارع", ""),
                            Neighbourhood(686, "القنا جنوب", ""),
                            Neighbourhood(687, "القنا شمال", ""),
                            Neighbourhood(690, "القوز جنوب مربع 3-4", ""),
                            Neighbourhood(691, "القوز شمال أ", ""),
                            Neighbourhood(692, "القوز شمال ب", ""),
                            Neighbourhood(693, "القوز مربع 5", ""),
                            Neighbourhood(694, "القوز مربع 6", ""),
                            Neighbourhood(723, "اللاماب جنوب", ""),
                            Neighbourhood(724, "اللاماب شمال", ""),
                            Neighbourhood(726, "المايقوما", ""),
                            Neighbourhood(729, "المجاهدين", ""),
                            Neighbourhood(737, "المزاد والشعبية", ""),
                            Neighbourhood(738, "المساكن والشرطة الموحدة", ""),
                            Neighbourhood(744, "المعرض", ""),
                            Neighbourhood(745, "المعمورة جنوب", ""),
                            Neighbourhood(746, "المعمورة شرق", ""),
                            Neighbourhood(750, "المقرن شرق", ""),
                            Neighbourhood(751, "المقرن غرب", ""),
                            Neighbourhood(761, "المنشية مربع 25", ""),
                            Neighbourhood(779, "النزهة", ""),
                            Neighbourhood(878, "امتداد ناصر جنوب", ""),
                            Neighbourhood(879, "امتداد ناصر شمال", ""),
                            Neighbourhood(900, "برتى والعطا شرق", ""),
                            Neighbourhood(901, "برتى والعطا غرب", ""),
                            Neighbourhood(904, "بري ابو حشيش", ""),
                            Neighbourhood(905, "بري الدرايسة", ""),
                            Neighbourhood(906, "بري اللاماب", ""),
                            Neighbourhood(907, "بري المحس", ""),
                            Neighbourhood(908, "بري كوريا", ""),
                            Neighbourhood(922, "توتي", ""),
                            Neighbourhood(924, "جبرة  جنوب م13-14-15-16-17", ""),
                            Neighbourhood(925, "جبرة  جنوب م18-19-20", ""),
                            Neighbourhood(926, "جبرة  شمال م1-2-3", ""),
                            Neighbourhood(927, "جبرة  شمال م10-11-12", ""),
                            Neighbourhood(928, "جبرة شمال  م4-5-6-8-9", ""),
                            Neighbourhood(941, "حى الزهور", ""),
                            Neighbourhood(962, "حي المطار", ""),
                            Neighbourhood(990, "سلاح المدرعات", ""),
                            Neighbourhood(994, "سوبا الحلة م1-2", ""),
                            Neighbourhood(995, "سوبا الحلة م3-4", ""),
                            Neighbourhood(996, "سوبا الحلة م5-6", ""),
                            Neighbourhood(997, "سوبا الحلة م7-8", ""),
                            Neighbourhood(998, "سوبا الشاحنات", ""),
                            Neighbourhood(999, "سوبا اللعوتة م1-2", ""),
                            Neighbourhood(1000, "سوبا اللعوتة م3", ""),
                            Neighbourhood(1001, "سوبا المحطة م1", ""),
                            Neighbourhood(1002, "سوبا المحطة م2", ""),
                            Neighbourhood(1003, "سوبا المحطة م3", ""),
                            Neighbourhood(1058, "غابة السنط", ""),
                            Neighbourhood(1064, "قاردن سيتي", ""),
                            Neighbourhood(1079, "قشلاق المدرعات", ""),
                            Neighbourhood(1098, "كمبو الصابرين- السجن", ""),
                            Neighbourhood(1250, "ود عجيب", ""),
                            Neighbourhood(1268, "يثرب", "")
                    )),
                    District(4, "شرق النيل", "", arrayListOf(
                            Neighbourhood(4, " الدلو", ""),
                            Neighbourhood(7, " نور الاسلام", ""),
                            Neighbourhood(21, "ابو قرون جنوب غرب", ""),
                            Neighbourhood(22, "ابو قرون شرق", ""),
                            Neighbourhood(23, "ابو قرون وسط", ""),
                            Neighbourhood(34, "ابوزليق", ""),
                            Neighbourhood(35, "ابوصالح شرق", ""),
                            Neighbourhood(54, "الاحامدة شرق", ""),
                            Neighbourhood(55, "الاحامدة غرب", ""),
                            Neighbourhood(56, "الاحامده الفريش", ""),
                            Neighbourhood(57, "الاحامده الوادى", ""),
                            Neighbourhood(58, "الاحامده ام عرف", ""),
                            Neighbourhood(59, "الاحامده شمال", ""),
                            Neighbourhood(84, "الالبان شرق", ""),
                            Neighbourhood(85, "الالبان غرب", ""),
                            Neighbourhood(87, "الامتداد جنوب شرق", ""),
                            Neighbourhood(88, "الامتداد جنوب غرب", ""),
                            Neighbourhood(89, "الامتداد شمال شرق", ""),
                            Neighbourhood(90, "الامتداد شمال غرب", ""),
                            Neighbourhood(116, "الباقر شرق", ""),
                            Neighbourhood(117, "الباكراب", ""),
                            Neighbourhood(120, "البدواب", ""),
                            Neighbourhood(121, "البركات شمال", ""),
                            Neighbourhood(122, "البركات مربع 1", ""),
                            Neighbourhood(123, "البركات مربع2", ""),
                            Neighbourhood(124, "البركات مربع3", ""),
                            Neighbourhood(125, "البركات مربع4", ""),
                            Neighbourhood(129, "البنبوناب ب ام ضوابان", ""),
                            Neighbourhood(130, "البنوناب ب وادي ابو صالح", ""),
                            Neighbourhood(133, "البياضة ود جبارة الله", ""),
                            Neighbourhood(136, "التبراب", ""),
                            Neighbourhood(138, "التريتيره والزيداب", ""),
                            Neighbourhood(146, "التعويضات", ""),
                            Neighbourhood(147, "التعويضات 3-4", ""),
                            Neighbourhood(148, "التعويضات5-6", ""),
                            Neighbourhood(150, "التكناب", ""),
                            Neighbourhood(152, "التلال", ""),
                            Neighbourhood(153, "التويراب", ""),
                            Neighbourhood(164, "الجبارين", ""),
                            Neighbourhood(166, "الجريف شرق مربع 1 جنوب", ""),
                            Neighbourhood(167, "الجريف شرق مربع 1 شمال", ""),
                            Neighbourhood(168, "الجريف شرق مربع 1 غرب", ""),
                            Neighbourhood(169, "الجريف شرق مربع 2 شرق", ""),
                            Neighbourhood(170, "الجريف شرق مربع 3 غرب", ""),
                            Neighbourhood(181, "الجلياب", ""),
                            Neighbourhood(182, "الجمعوناب", ""),
                            Neighbourhood(184, "الجميلية", ""),
                            Neighbourhood(185, "الجنيب", ""),
                            Neighbourhood(190, "الحاج يوسف", ""),
                            Neighbourhood(191, "الحاج يوسف شرق", ""),
                            Neighbourhood(192, "الحاج يوسف شمال", ""),
                            Neighbourhood(336, "الحديبة", ""),
                            Neighbourhood(337, "الحرابةوالزياييت", ""),
                            Neighbourhood(340, "الحسانية", ""),
                            Neighbourhood(342, "الحسناب", ""),
                            Neighbourhood(343, "الحسوباب جنوب", ""),
                            Neighbourhood(344, "الحسوباب شمال", ""),
                            Neighbourhood(346, "الحفرة السلام", ""),
                            Neighbourhood(347, "الحفرة شرق", ""),
                            Neighbourhood(348, "الحفرة غرب", ""),
                            Neighbourhood(374, "الحور-الجدياب", ""),
                            Neighbourhood(376, "الحويلة", ""),
                            Neighbourhood(390, "الدبابة", ""),
                            Neighbourhood(411, "الدقلاب", ""),
                            Neighbourhood(412, "الدلتية", ""),
                            Neighbourhood(413, "الدلجة الشيخ النيل", ""),
                            Neighbourhood(421, "الدومة", ""),
                            Neighbourhood(423, "الدويكلة", ""),
                            Neighbourhood(447, "الزيناب", ""),
                            Neighbourhood(463, "السدير", ""),
                            Neighbourhood(468, "السريره", ""),
                            Neighbourhood(470, "السعيداب", ""),
                            Neighbourhood(476, "السلام جنوب", ""),
                            Neighbourhood(478, "السلام شمال", ""),
                            Neighbourhood(480, "السلامة شمال", ""),
                            Neighbourhood(491, "السمرة جنوب", ""),
                            Neighbourhood(492, "السمرة شمال", ""),
                            Neighbourhood(495, "السمير", ""),
                            Neighbourhood(508, "الشروق", ""),
                            Neighbourhood(509, "الشريق", ""),
                            Neighbourhood(515, "الشقلة ابو القاسم", ""),
                            Neighbourhood(517, "الشقلة شمال", ""),
                            Neighbourhood(527, "الشليخة", ""),
                            Neighbourhood(535, "الشيخ الأمين", ""),
                            Neighbourhood(540, "الشيخ طه", ""),
                            Neighbourhood(541, "الشيخ عوض الكريم جنوب", ""),
                            Neighbourhood(542, "الشيخ عوض الكريم شمال", ""),
                            Neighbourhood(543, "الشيخ عوض الكريم وسط", ""),
                            Neighbourhood(544, "الصاحباب", ""),
                            Neighbourhood(561, "الصفاء جنوب", ""),
                            Neighbourhood(562, "الصفاء شمال", ""),
                            Neighbourhood(566, "الضريساب", ""),
                            Neighbourhood(570, "الطلحة سعادة", ""),
                            Neighbourhood(572, "العالماب", ""),
                            Neighbourhood(581, "العد الجديد", ""),
                            Neighbourhood(585, "العرقوب", ""),
                            Neighbourhood(586, "العرقوب وعد ستنا والنخيره", ""),
                            Neighbourhood(587, "العريطلاب والصاحباب", ""),
                            Neighbourhood(588, "العريقيب", ""),
                            Neighbourhood(592, "العشراب", ""),
                            Neighbourhood(597, "العصياب", ""),
                            Neighbourhood(609, "الغابة", ""),
                            Neighbourhood(610, "الغابة وسط", ""),
                            Neighbourhood(614, "الفادني جنوب", ""),
                            Neighbourhood(615, "الفادني شمال", ""),
                            Neighbourhood(616, "الفادني وسط", ""),
                            Neighbourhood(618, "الفاروق", ""),
                            Neighbourhood(639, "الفروجاب", ""),
                            Neighbourhood(642, "الفريع", ""),
                            Neighbourhood(643, "الفريع الرحل", ""),
                            Neighbourhood(644, "الفريع مهلة", ""),
                            Neighbourhood(647, "الفصيلاب ود التقيل", ""),
                            Neighbourhood(651, "الفيحاء", ""),
                            Neighbourhood(665, "القرنباب", ""),
                            Neighbourhood(666, "القروناب", ""),
                            Neighbourhood(667, "القسملاب", ""),
                            Neighbourhood(668, "القطاطي", ""),
                            Neighbourhood(673, "القلابات", ""),
                            Neighbourhood(676, "القلعة أم علية والعكشاب", ""),
                            Neighbourhood(688, "القناجبة", ""),
                            Neighbourhood(689, "القوز", ""),
                            Neighbourhood(695, "القويز", ""),
                            Neighbourhood(705, "الكديوه", ""),
                            Neighbourhood(707, "الكربه", ""),
                            Neighbourhood(708, "الكرداب النموزجيه", ""),
                            Neighbourhood(709, "الكرداب الوحده", ""),
                            Neighbourhood(710, "الكرداب الوحده والكيداب", ""),
                            Neighbourhood(711, "الكرنوس", ""),
                            Neighbourhood(712, "الكرياب", ""),
                            Neighbourhood(720, "الكوراب", ""),
                            Neighbourhood(727, "المايقوما شرق", ""),
                            Neighbourhood(728, "المايقوما غرب جنوب", ""),
                            Neighbourhood(730, "المحس طيبة", ""),
                            Neighbourhood(731, "المحس كترانج", ""),
                            Neighbourhood(732, "المديمير", ""),
                            Neighbourhood(733, "المرابيع", ""),
                            Neighbourhood(734, "المرابيع-ام جرا", ""),
                            Neighbourhood(755, "المنارة", ""),
                            Neighbourhood(777, "النابية", ""),
                            Neighbourhood(780, "النصر", ""),
                            Neighbourhood(797, "الهديباب جنوب", ""),
                            Neighbourhood(798, "الهديباب شمال", ""),
                            Neighbourhood(809, "الوحدة شرق", ""),
                            Neighbourhood(810, "الوحدة غرب", ""),
                            Neighbourhood(819, "الوشام", ""),
                            Neighbourhood(831, "ام تبسة-الخور", ""),
                            Neighbourhood(832, "ام جحف", ""),
                            Neighbourhood(835, "ام حجرا", ""),
                            Neighbourhood(836, "ام حجره والسهلاب", ""),
                            Neighbourhood(838, "ام ريل", ""),
                            Neighbourhood(841, "ام سيالة والظليلة", ""),
                            Neighbourhood(849, "ام ضوابان جنوب شرق", ""),
                            Neighbourhood(850, "ام ضوابان جنوب غرب", ""),
                            Neighbourhood(851, "ام ضوابان شرق", ""),
                            Neighbourhood(852, "ام ضوابان شمال شرق", ""),
                            Neighbourhood(853, "ام ضوابان شمال غرب", ""),
                            Neighbourhood(854, "ام ضوابان وسط", ""),
                            Neighbourhood(857, "ام عشوش", ""),
                            Neighbourhood(858, "ام عشيرة", ""),
                            Neighbourhood(862, "ام كترة", ""),
                            Neighbourhood(868, "امتداد الجريف شرق", ""),
                            Neighbourhood(871, "امتداد العيلفون", ""),
                            Neighbourhood(874, "امتداد حلة كوكو", ""),
                            Neighbourhood(892, "أم دوم", ""),
                            Neighbourhood(909, "بشاير-السليم", ""),
                            Neighbourhood(929, "جبرونا", ""),
                            Neighbourhood(935, "حطاب شرق", ""),
                            Neighbourhood(936, "حطاب غرب", ""),
                            Neighbourhood(939, "حلة كوكو مربع", ""),
                            Neighbourhood(940, "حلة كوكو مربع 10و11", ""),
                            Neighbourhood(943, "حي الاسكان", ""),
                            Neighbourhood(944, "حي الاسلام", ""),
                            Neighbourhood(945, "حي الانقاذ", ""),
                            Neighbourhood(947, "حي التكامل", ""),
                            Neighbourhood(948, "حي الجوبا", ""),
                            Neighbourhood(949, "حي الحجاج", ""),
                            Neighbourhood(950, "حي الدوحة", ""),
                            Neighbourhood(951, "حي الشاطئ", ""),
                            Neighbourhood(952, "حي الشرطة", ""),
                            Neighbourhood(953, "حي الصالحين", ""),
                            Neighbourhood(958, "حي الفلاح", ""),
                            Neighbourhood(959, "حي الكوثر", ""),
                            Neighbourhood(960, "حي المزدلفة", ""),
                            Neighbourhood(961, "حي المصطفي", ""),
                            Neighbourhood(963, "حي المنصورة", ""),
                            Neighbourhood(965, "حي مطفي ابوالقاسم", ""),
                            Neighbourhood(969, "دار السلام المغاربة", ""),
                            Neighbourhood(979, "رام الله", ""),
                            Neighbourhood(980, "ربوب ابو ملوه", ""),
                            Neighbourhood(981, "ربوب العد", ""),
                            Neighbourhood(982, "ريحانة", ""),
                            Neighbourhood(983, "سترة", ""),
                            Neighbourhood(984, "سترة الورا-البلكة", ""),
                            Neighbourhood(986, "سرحان شرق", ""),
                            Neighbourhood(987, "سرحان غرب", ""),
                            Neighbourhood(992, "سلمه ود نايل", ""),
                            Neighbourhood(1008, "سيال الحواب", ""),
                            Neighbourhood(1009, "سيال الفكى السيد", ""),
                            Neighbourhood(1010, "سيال الفكى سعد", ""),
                            Neighbourhood(1014, "شقلة رادو", ""),
                            Neighbourhood(1030, "عد الحاج جنوب", ""),
                            Neighbourhood(1031, "عد الحاج شمال", ""),
                            Neighbourhood(1038, "عد القنيعاب", ""),
                            Neighbourhood(1040, "عد الكرامة", ""),
                            Neighbourhood(1041, "عد ام دوم", ""),
                            Neighbourhood(1042, "عد بابكر جنوب", ""),
                            Neighbourhood(1043, "عد بابكر شمال شرق", ""),
                            Neighbourhood(1044, "عد بابكر شمال غرب", ""),
                            Neighbourhood(1045, "عد بابكر وسط", ""),
                            Neighbourhood(1052, "علوان", ""),
                            Neighbourhood(1053, "علوان ابريم", ""),
                            Neighbourhood(1054, "علوان حى العمده", ""),
                            Neighbourhood(1057, "عيد شروم", ""),
                            Neighbourhood(1084, "قوز الطاهر", ""),
                            Neighbourhood(1088, "كترانج", ""),
                            Neighbourhood(1093, "كركوج جنوب شرق", ""),
                            Neighbourhood(1094, "كركوج جنوب وسط", ""),
                            Neighbourhood(1095, "كركوج شمال 1", ""),
                            Neighbourhood(1096, "كركوج شمال 2", ""),
                            Neighbourhood(1097, "كركوج شمال3", ""),
                            Neighbourhood(1105, "لتمامه", ""),
                            Neighbourhood(1107, "ما تكلي", ""),
                            Neighbourhood(1112, "مبروكه", ""),
                            Neighbourhood(1222, "نابلس", ""),
                            Neighbourhood(1231, "ود الامين شرق", ""),
                            Neighbourhood(1232, "ود الامين غرب", ""),
                            Neighbourhood(1240, "ود بخيت", ""),
                            Neighbourhood(1243, "ود دفيعة شرق", ""),
                            Neighbourhood(1244, "ود دفيعة غرب", ""),
                            Neighbourhood(1245, "ود دفيعة وسط", ""),
                            Neighbourhood(1249, "ود سرار", ""),
                            Neighbourhood(1251, "ود عجيل", ""),
                            Neighbourhood(1255, "ود مولي", ""),
                            Neighbourhood(1260, "ودابوصالح غرب", ""),
                            Neighbourhood(1261, "وداصول الفرع", ""),
                            Neighbourhood(1262, "ودالبشير شرق", ""),
                            Neighbourhood(1263, "ودالبشير غرب", ""),
                            Neighbourhood(1264, "ودالحاج جنوب", ""),
                            Neighbourhood(1265, "ودتبار", ""),
                            Neighbourhood(1266, "ودشوين", ""),
                            Neighbourhood(1267, "يافا", "")
                    )),
                    District(5, "جبل أولياء", "", arrayListOf(
                            Neighbourhood(6, " النصر غرب ح14/ب", ""),
                            Neighbourhood(9, "ابو ايوب م1-2-3", ""),
                            Neighbourhood(10, "ابو ايوب م4", ""),
                            Neighbourhood(11, "ابو ايوب م5", ""),
                            Neighbourhood(12, "ابو ايوب م6", ""),
                            Neighbourhood(14, "ابو دروس", ""),
                            Neighbourhood(17, "ابو ضريس", ""),
                            Neighbourhood(37, "اراك الكاتب", ""),
                            Neighbourhood(38, "اراك صالح", ""),
                            Neighbourhood(60, "الازهري م1-7", ""),
                            Neighbourhood(61, "الازهري م10", ""),
                            Neighbourhood(62, "الازهري م11", ""),
                            Neighbourhood(63, "الازهري م12", ""),
                            Neighbourhood(64, "الازهري م13", ""),
                            Neighbourhood(65, "الازهري م14", ""),
                            Neighbourhood(66, "الازهري م15", ""),
                            Neighbourhood(67, "الازهري م16", ""),
                            Neighbourhood(68, "الازهري م17", ""),
                            Neighbourhood(69, "الازهري م19-20", ""),
                            Neighbourhood(70, "الازهري م2-6", ""),
                            Neighbourhood(71, "الازهري م21-22", ""),
                            Neighbourhood(72, "الازهري م23", ""),
                            Neighbourhood(73, "الازهري م24-25", ""),
                            Neighbourhood(74, "الازهري م35 الشاحنات", ""),
                            Neighbourhood(75, "الازهري م8", ""),
                            Neighbourhood(76, "الازهري م9", ""),
                            Neighbourhood(98, "الاندلس جنوب", ""),
                            Neighbourhood(99, "الاندلس م12", ""),
                            Neighbourhood(100, "الاندلس م3", ""),
                            Neighbourhood(101, "الاندلس م7", ""),
                            Neighbourhood(102, "الاندلس م8", ""),
                            Neighbourhood(103, "الاندلس م9", ""),
                            Neighbourhood(107, "الانقاذ م1شرق", ""),
                            Neighbourhood(108, "الانقاذ م1غرب", ""),
                            Neighbourhood(109, "الانقاذ م2 غرب", ""),
                            Neighbourhood(110, "الانقاذ م2شرق", ""),
                            Neighbourhood(111, "الانقاذ م3جنوب", ""),
                            Neighbourhood(112, "الانقاذ م3شمال", ""),
                            Neighbourhood(113, "الانقاذ م4شرق", ""),
                            Neighbourhood(114, "الانقاذ م4غرب", ""),
                            Neighbourhood(118, "البجة عبد الهادي", ""),
                            Neighbourhood(140, "التريعة جنوب م13", ""),
                            Neighbourhood(141, "التريعة شرق م11", ""),
                            Neighbourhood(142, "التريعة غرب م12", ""),
                            Neighbourhood(352, "الحلة الجديدة جنوب", ""),
                            Neighbourhood(355, "الحلة الجديدة شمال", ""),
                            Neighbourhood(357, "الحلة الجديدة م4 شرق", ""),
                            Neighbourhood(358, "الحلة الجديدة م4غرب", ""),
                            Neighbourhood(395, "الدخينات  العوامرة غرب", ""),
                            Neighbourhood(396, "الدخينات شرق العميد", ""),
                            Neighbourhood(422, "الدويحية", ""),
                            Neighbourhood(424, "الدية الشيخ حبيب", ""),
                            Neighbourhood(446, "الزهراء", ""),
                            Neighbourhood(474, "السكة حديد", ""),
                            Neighbourhood(477, "السلام شرق", ""),
                            Neighbourhood(479, "السلام غرب", ""),
                            Neighbourhood(484, "السلمة م1", ""),
                            Neighbourhood(485, "السلمة م2", ""),
                            Neighbourhood(486, "السلمة م3", ""),
                            Neighbourhood(487, "السليكاب", ""),
                            Neighbourhood(489, "السليمانية شرق", ""),
                            Neighbourhood(514, "الشقلاب ام حراز", ""),
                            Neighbourhood(519, "الشقيلاب الجرف", ""),
                            Neighbourhood(520, "الشقيلاب الحريز", ""),
                            Neighbourhood(521, "الشقيلاب الحسانية", ""),
                            Neighbourhood(522, "الشقيلاب الخور", ""),
                            Neighbourhood(523, "الشقيلاب الغربية", ""),
                            Neighbourhood(524, "الشقيلاب القصيرة", ""),
                            Neighbourhood(539, "الشيخ حامد", ""),
                            Neighbourhood(563, "الصفوة", ""),
                            Neighbourhood(591, "العسال", ""),
                            Neighbourhood(619, "الفاروق م1", ""),
                            Neighbourhood(620, "الفاروق م2-4-11", ""),
                            Neighbourhood(621, "الفاروق م3-10", ""),
                            Neighbourhood(622, "الفاروق م5-6-7-8-9", ""),
                            Neighbourhood(633, "الفتح المبين", ""),
                            Neighbourhood(648, "الفكي دفع الله", ""),
                            Neighbourhood(652, "الفيلاب", ""),
                            Neighbourhood(653, "القادسية", ""),
                            Neighbourhood(654, "القبة جنوب م6", ""),
                            Neighbourhood(655, "القبة جنوب م7", ""),
                            Neighbourhood(656, "القبة جنوب م8", ""),
                            Neighbourhood(657, "القبة شمال م1-2", ""),
                            Neighbourhood(658, "القبة شمال م3-5", ""),
                            Neighbourhood(659, "القبة شمال م4", ""),
                            Neighbourhood(660, "القبة غرب م10أ", ""),
                            Neighbourhood(661, "القبة غرب م10ب", ""),
                            Neighbourhood(662, "القبة غرب م9", ""),
                            Neighbourhood(663, "القبة م14", ""),
                            Neighbourhood(669, "القطعية م1", ""),
                            Neighbourhood(670, "القطعية م2", ""),
                            Neighbourhood(671, "القطعية م3-5", ""),
                            Neighbourhood(672, "القطعية م4", ""),
                            Neighbourhood(677, "القلعة جنوب", ""),
                            Neighbourhood(678, "القلعة شمال", ""),
                            Neighbourhood(679, "القلعة غرب", ""),
                            Neighbourhood(680, "القلعة وسط", ""),
                            Neighbourhood(697, "الكبابيش جنوب", ""),
                            Neighbourhood(698, "الكبابيش شمال", ""),
                            Neighbourhood(741, "المسيد الحسناب", ""),
                            Neighbourhood(760, "المنشاء", ""),
                            Neighbourhood(762, "المنصورة م1", ""),
                            Neighbourhood(763, "المنصورة م3", ""),
                            Neighbourhood(766, "المنورة", ""),
                            Neighbourhood(781, "النصر شمال", ""),
                            Neighbourhood(782, "النصر غرب ح12", ""),
                            Neighbourhood(783, "النصر غرب ح13", ""),
                            Neighbourhood(784, "النصر غرب ح14/أ", ""),
                            Neighbourhood(785, "النصر غرب ح15", ""),
                            Neighbourhood(786, "النصر وسط ح7", ""),
                            Neighbourhood(787, "النصر وسط ح8", ""),
                            Neighbourhood(788, "النصر وسط ح8 شرق", ""),
                            Neighbourhood(789, "النصر وسط ح9", ""),
                            Neighbourhood(791, "النوبة الحسناب", ""),
                            Neighbourhood(811, "الوحدة م1", ""),
                            Neighbourhood(812, "الوحدة م2", ""),
                            Neighbourhood(813, "الوحدة م3", ""),
                            Neighbourhood(814, "الوحدة م4", ""),
                            Neighbourhood(815, "الوحدة م5", ""),
                            Neighbourhood(816, "الوحدة م6", ""),
                            Neighbourhood(817, "الوحدة م7", ""),
                            Neighbourhood(820, "اليرموك م4-5", ""),
                            Neighbourhood(821, "اليرموك م7", ""),
                            Neighbourhood(837, "ام رباح", ""),
                            Neighbourhood(855, "ام عشر شرق", ""),
                            Neighbourhood(856, "ام عشر غرب", ""),
                            Neighbourhood(861, "ام قرقير", ""),
                            Neighbourhood(867, "امتداد البجة", ""),
                            Neighbourhood(869, "امتداد الحلة الجديدة", ""),
                            Neighbourhood(870, "امتداد الحلة الجديدة م3", ""),
                            Neighbourhood(875, "امتداد ديم البساطاب", ""),
                            Neighbourhood(898, "بدر1 ح16", ""),
                            Neighbourhood(899, "بدر2", ""),
                            Neighbourhood(919, "تريعة البجة", ""),
                            Neighbourhood(920, "تريعة الحسناب", ""),
                            Neighbourhood(946, "حي التجار", ""),
                            Neighbourhood(964, "حي الوادي", ""),
                            Neighbourhood(970, "دار السلام م1", ""),
                            Neighbourhood(971, "دار السلام م2", ""),
                            Neighbourhood(972, "دار السلام م3", ""),
                            Neighbourhood(973, "دار السلام م4", ""),
                            Neighbourhood(976, "ديم البساطاب جنوب", ""),
                            Neighbourhood(977, "ديم البساطاب شرق", ""),
                            Neighbourhood(978, "ديم البساطاب غرب", ""),
                            Neighbourhood(993, "سوبا الاراضي", ""),
                            Neighbourhood(1005, "سوق اللفة", ""),
                            Neighbourhood(1006, "سوق بشاير", ""),
                            Neighbourhood(1015, "شكر الله", ""),
                            Neighbourhood(1022, "صنقعت شرق", ""),
                            Neighbourhood(1023, "صنقعت غر ب", ""),
                            Neighbourhood(1029, "طيبة الحسناب", ""),
                            Neighbourhood(1046, "عد حسين م1", ""),
                            Neighbourhood(1047, "عد حسين م3", ""),
                            Neighbourhood(1048, "عد حسين م4شرق", ""),
                            Neighbourhood(1049, "عد حسين م4غرب", ""),
                            Neighbourhood(1050, "عسيلي", ""),
                            Neighbourhood(1059, "غمار", ""),
                            Neighbourhood(1061, "فتيح العقليين شرق", ""),
                            Neighbourhood(1062, "فتيح العقليين غرب", ""),
                            Neighbourhood(1063, "فتيح العقليين وسط", ""),
                            Neighbourhood(1065, "قبل جاي", ""),
                            Neighbourhood(1089, "كجبي حاج احمد", ""),
                            Neighbourhood(1099, "كمبو الضو", ""),
                            Neighbourhood(1106, "لنصر جنوب شرق م6", ""),
                            Neighbourhood(1108, "مايو السلام وسط", ""),
                            Neighbourhood(1109, "مايو جنوب غرب", ""),
                            Neighbourhood(1110, "مايو شرق أ", ""),
                            Neighbourhood(1111, "مايو شرق ب", ""),
                            Neighbourhood(1113, "مدينة الامل", ""),
                            Neighbourhood(1218, "مسرة", ""),
                            Neighbourhood(1238, "ود العقلي", ""),
                            Neighbourhood(1239, "ود النقيدة", ""),
                            Neighbourhood(1241, "ود بلول", ""),
                            Neighbourhood(1252, "ود عمارة ح1", ""),
                            Neighbourhood(1253, "ود عمارة ح2", ""),
                            Neighbourhood(1254, "ود مختار", ""),
                            Neighbourhood(1256, "ود نعيم", "")
                    )),
                    District(6, "بحري", "", arrayListOf(
                            Neighbourhood(8, "ابو العافض", ""),
                            Neighbourhood(13, "ابو حليمة و السروجية", ""),
                            Neighbourhood(18, "ابو طليح", ""),
                            Neighbourhood(24, "ابو قيدوم", ""),
                            Neighbourhood(25, "ابو قيدوم جنوب", ""),
                            Neighbourhood(51, "الابيض", ""),
                            Neighbourhood(53, "الاحامدة السليت", ""),
                            Neighbourhood(77, "الازيرقاب", ""),
                            Neighbourhood(81, "الاسيداب", ""),
                            Neighbourhood(96, "الاملاك شرق", ""),
                            Neighbourhood(97, "الاملاك غرب", ""),
                            Neighbourhood(105, "الانقاذ جنوب", ""),
                            Neighbourhood(106, "الانقاذ شمال", ""),
                            Neighbourhood(137, "التبنة", ""),
                            Neighbourhood(151, "التكينة ود عثمان", ""),
                            Neighbourhood(154, "الثمانيات شرق", ""),
                            Neighbourhood(155, "الثمانيات غرب", ""),
                            Neighbourhood(180, "الجعليين", ""),
                            Neighbourhood(187, "الجيلى جنوب", ""),
                            Neighbourhood(188, "الجيلى شمال", ""),
                            Neighbourhood(189, "الجيلى وسط", ""),
                            Neighbourhood(338, "الحرازة", ""),
                            Neighbourhood(341, "الحسانية السليت", ""),
                            Neighbourhood(361, "الحلفايا الحي1", ""),
                            Neighbourhood(362, "الحلفايا الحي10", ""),
                            Neighbourhood(363, "الحلفايا الحي2", ""),
                            Neighbourhood(364, "الحلفايا الحي3", ""),
                            Neighbourhood(365, "الحلفايا الحي4", ""),
                            Neighbourhood(366, "الحلفايا الحي5", ""),
                            Neighbourhood(367, "الحلفايا الحي6", ""),
                            Neighbourhood(368, "الحلفايا الحي7", ""),
                            Neighbourhood(369, "الحلفايا الحي8", ""),
                            Neighbourhood(370, "الحلفايا الحي9", ""),
                            Neighbourhood(373, "الحواويت", ""),
                            Neighbourhood(377, "الختمية جنوب", ""),
                            Neighbourhood(378, "الختمية شمال", ""),
                            Neighbourhood(385, "الخليلة", ""),
                            Neighbourhood(386, "الخمجاب اولاد مختار", ""),
                            Neighbourhood(387, "الخوارنة والحكيرة", ""),
                            Neighbourhood(388, "الخوجلاب", ""),
                            Neighbourhood(389, "الخيرلاب", ""),
                            Neighbourhood(394, "الدبة العبدلاب", ""),
                            Neighbourhood(397, "الدروشاب الروضة شرق", ""),
                            Neighbourhood(398, "الدروشاب الروضة غرب", ""),
                            Neighbourhood(399, "الدروشاب الشهداء", ""),
                            Neighbourhood(400, "الدروشاب العربي", ""),
                            Neighbourhood(401, "الدروشاب المنار", ""),
                            Neighbourhood(402, "الدروشاب النهضة", ""),
                            Neighbourhood(403, "الدروشاب جنوب شرق", ""),
                            Neighbourhood(404, "الدروشاب جنوب مربع1", ""),
                            Neighbourhood(405, "الدروشاب جنوب مربع2/أ", ""),
                            Neighbourhood(406, "الدروشاب جنوب مربع2/ب", ""),
                            Neighbourhood(407, "الدروشاب شمال", ""),
                            Neighbourhood(408, "الدروشاب شمال شرق", ""),
                            Neighbourhood(415, "الدناقلة جنوب", ""),
                            Neighbourhood(416, "الدناقلة شمال", ""),
                            Neighbourhood(417, "الدهم", ""),
                            Neighbourhood(420, "الدوم", ""),
                            Neighbourhood(438, "الرويان", ""),
                            Neighbourhood(444, "الزاكياب الفردوس", ""),
                            Neighbourhood(445, "الزاكياب وسط وجنوب", ""),
                            Neighbourhood(449, "السامراب الشهداء", ""),
                            Neighbourhood(450, "السامراب الصفا", ""),
                            Neighbourhood(451, "السامراب الفاروق", ""),
                            Neighbourhood(452, "السامراب النصر", ""),
                            Neighbourhood(453, "السامراب النهضة", ""),
                            Neighbourhood(454, "السامراب الهدى", ""),
                            Neighbourhood(455, "السامراب الوفاق", ""),
                            Neighbourhood(456, "السامراب عباد الرحمن", ""),
                            Neighbourhood(471, "السقاي الانصار", ""),
                            Neighbourhood(472, "السقاي البتلاب", ""),
                            Neighbourhood(473, "السقاي السروراب", ""),
                            Neighbourhood(481, "السلمة التعويضات", ""),
                            Neighbourhood(482, "السلمة جنوب", ""),
                            Neighbourhood(483, "السلمة شمال", ""),
                            Neighbourhood(490, "السمرة الخلفاب", ""),
                            Neighbourhood(500, "الشايقية", ""),
                            Neighbourhood(510, "الشعبية جنوب", ""),
                            Neighbourhood(511, "الشعبية شمال", ""),
                            Neighbourhood(512, "الشفيعاب و الكرداب", ""),
                            Neighbourhood(526, "الشلعاب", ""),
                            Neighbourhood(528, "الشهداء", ""),
                            Neighbourhood(545, "الصافية جنوب", ""),
                            Neighbourhood(546, "الصافية شمال", ""),
                            Neighbourhood(547, "الصبابي", ""),
                            Neighbourhood(598, "العطيفة", ""),
                            Neighbourhood(600, "العكيرة", ""),
                            Neighbourhood(601, "العلوياب", ""),
                            Neighbourhood(611, "الغار", ""),
                            Neighbourhood(640, "الفريش جنوب", ""),
                            Neighbourhood(641, "الفريش شمال", ""),
                            Neighbourhood(645, "الفزراب", ""),
                            Neighbourhood(646, "الفزراب الاحامدة", ""),
                            Neighbourhood(650, "الفكي هاشم", ""),
                            Neighbourhood(700, "الكباشى", ""),
                            Neighbourhood(702, "الكدرو جنوب", ""),
                            Neighbourhood(703, "الكدرو شمال", ""),
                            Neighbourhood(704, "الكدرو وسط", ""),
                            Neighbourhood(713, "الكسر و خور المجاهد", ""),
                            Neighbourhood(714, "الكمر", ""),
                            Neighbourhood(716, "الكنجر", ""),
                            Neighbourhood(735, "المزاد جنوب", ""),
                            Neighbourhood(736, "المزاد شمال", ""),
                            Neighbourhood(747, "المغتربين جنوب", ""),
                            Neighbourhood(748, "المغتربين شمال", ""),
                            Neighbourhood(776, "الميرغنية", ""),
                            Neighbourhood(778, "النخيلة", ""),
                            Neighbourhood(793, "النية", ""),
                            Neighbourhood(795, "الهجرة", ""),
                            Neighbourhood(800, "الوابورات", ""),
                            Neighbourhood(801, "الواحة", ""),
                            Neighbourhood(807, "الوادي", ""),
                            Neighbourhood(823, "ام القرى التضامن", ""),
                            Neighbourhood(824, "ام القرى الجرافة", ""),
                            Neighbourhood(825, "ام القرى جنوب", ""),
                            Neighbourhood(826, "ام القرى شمال شرق", ""),
                            Neighbourhood(827, "ام القرى غرب الجديدة", ""),
                            Neighbourhood(828, "ام القرى غرب القديمة", ""),
                            Neighbourhood(829, "ام القرى وسط", ""),
                            Neighbourhood(830, "ام بشار", ""),
                            Neighbourhood(839, "ام سدرة", ""),
                            Neighbourhood(843, "ام ضريوة الاحامدة", ""),
                            Neighbourhood(844, "ام ضريوة الكبيراب", ""),
                            Neighbourhood(845, "ام ضريوة جنوب شرق", ""),
                            Neighbourhood(846, "ام ضريوة جنوب غرب", ""),
                            Neighbourhood(847, "ام ضريوة شمال", ""),
                            Neighbourhood(848, "ام ضريوة وسط", ""),
                            Neighbourhood(866, "ام ميكج", ""),
                            Neighbourhood(876, "امتداد شمبات جنوب", ""),
                            Neighbourhood(877, "امتداد شمبات شمال", ""),
                            Neighbourhood(882, "اولاد الامام", ""),
                            Neighbourhood(884, "اولاد الطعام", ""),
                            Neighbourhood(887, "اولاد حسيب", ""),
                            Neighbourhood(888, "اولاد يس", ""),
                            Neighbourhood(921, "تميم الاحامدة", ""),
                            Neighbourhood(930, "جبل جارى", ""),
                            Neighbourhood(937, "حلة حمد", ""),
                            Neighbourhood(938, "حلة خوجلي", ""),
                            Neighbourhood(966, "حيطة", ""),
                            Neighbourhood(968, "خور كتيرة", ""),
                            Neighbourhood(974, "دبك", ""),
                            Neighbourhood(975, "دردوق", ""),
                            Neighbourhood(985, "سجن كوبر", ""),
                            Neighbourhood(991, "سلمة الكباشي", ""),
                            Neighbourhood(1016, "شمبات الزراعة والمرسى", ""),
                            Neighbourhood(1017, "شمبات جنوب", ""),
                            Neighbourhood(1018, "شمبات شمال", ""),
                            Neighbourhood(1019, "شمبات غرب", ""),
                            Neighbourhood(1024, "طيبة الاحامدة مربع18", ""),
                            Neighbourhood(1025, "طيبة الاحامدة مربع19", ""),
                            Neighbourhood(1026, "طيبة الاحامدة مربع20", ""),
                            Neighbourhood(1027, "طيبة الاحامدة مربع21", ""),
                            Neighbourhood(1033, "عد الحش", ""),
                            Neighbourhood(1034, "عد الدلجة جنوب", ""),
                            Neighbourhood(1035, "عد الدلجة شمال", ""),
                            Neighbourhood(1036, "عد الروى", ""),
                            Neighbourhood(1039, "عد الكباشي", ""),
                            Neighbourhood(1066, "قرى التضامن", ""),
                            Neighbourhood(1067, "قرى الحسانية", ""),
                            Neighbourhood(1068, "قرى السلام", ""),
                            Neighbourhood(1077, "قشلاق الاشارة", ""),
                            Neighbourhood(1078, "قشلاق الشرطة", ""),
                            Neighbourhood(1080, "قلعة السليت", ""),
                            Neighbourhood(1083, "قلعة ود مالك", ""),
                            Neighbourhood(1087, "كافوري", ""),
                            Neighbourhood(1102, "كوبر شرق", ""),
                            Neighbourhood(1103, "كوبر شمال", ""),
                            Neighbourhood(1104, "كوبر غرب", ""),
                            Neighbourhood(1219, "مقابر", ""),
                            Neighbourhood(1220, "منطقة عسكرية", ""),
                            Neighbourhood(1224, "وادى العروس", ""),
                            Neighbourhood(1226, "واوسي الشيخ عبد القادر", ""),
                            Neighbourhood(1227, "واوسي الشيخ على", ""),
                            Neighbourhood(1228, "واوسي الوادي", ""),
                            Neighbourhood(1229, "واوسي غرب", ""),
                            Neighbourhood(1230, "واوسي وسط", ""),
                            Neighbourhood(1237, "ود السائح", ""),
                            Neighbourhood(1246, "ود رملي جنوب", ""),
                            Neighbourhood(1247, "ود رملي شمال", ""),
                            Neighbourhood(1248, "ود رملي وسط", "")
                    )),
                    District(7, "أم بده", "", arrayListOf(
                            Neighbourhood(80, "الاسكان الشعبي", ""),
                            Neighbourhood(83, "الاصلاح", ""),
                            Neighbourhood(104, "الانقاذ", ""),
                            Neighbourhood(127, "البشراب", ""),
                            Neighbourhood(128, "البلولاب", ""),
                            Neighbourhood(135, "التابراب", ""),
                            Neighbourhood(163, "الجباراب", ""),
                            Neighbourhood(216, "السلام الحارة 48", ""),
                            Neighbourhood(235, "الامير الحارة1", ""),
                            Neighbourhood(237, "الامير الحارة10", ""),
                            Neighbourhood(239, "الامير الحارة11", ""),
                            Neighbourhood(241, "الامير الحارة12", ""),
                            Neighbourhood(244, "البقعة الحارة13 الانفال", ""),
                            Neighbourhood(246, "البقعة الحارة14 الاصلاح", ""),
                            Neighbourhood(247, "البقعة الحارة14 التقوى", ""),
                            Neighbourhood(248, "البقعة الحارة14 الراشدين", ""),
                            Neighbourhood(249, "البقعة الحارة14 الريان", ""),
                            Neighbourhood(250, "البقعة الحارة14 الصحوة", ""),
                            Neighbourhood(251, "البقعة الحارة14 المنارة شرق", ""),
                            Neighbourhood(252, "البقعة الحارة14 المنارة غرب", ""),
                            Neighbourhood(253, "البقعة الحارة14 المنصورة", ""),
                            Neighbourhood(254, "البقعة الحارة14 بدرالكبرى", ""),
                            Neighbourhood(255, "البقعة الحارة14 حمد النيل", ""),
                            Neighbourhood(257, "الامير الحارة15/أ", ""),
                            Neighbourhood(258, "الامير الحارة15/ب", ""),
                            Neighbourhood(259, "الامير الحارة15/ج", ""),
                            Neighbourhood(261, "الامير الحارة16/أ", ""),
                            Neighbourhood(262, "الامير الحارة16/ب", ""),
                            Neighbourhood(263, "البقعة الحارة17 ابوزيد", ""),
                            Neighbourhood(264, "البقعة الحارة17 الازهر", ""),
                            Neighbourhood(265, "البقعة الحارة17 الراشدية", ""),
                            Neighbourhood(266, "البقعة الحارة17 الفردوس", ""),
                            Neighbourhood(267, "الامير الحارة18", ""),
                            Neighbourhood(268, "الامير الحارة19", ""),
                            Neighbourhood(269, "الامير الحارة2", ""),
                            Neighbourhood(271, "الامير الحارة20", ""),
                            Neighbourhood(272, "الامير الحارة21 شرق", ""),
                            Neighbourhood(273, "الامير الحارة21 غرب", ""),
                            Neighbourhood(275, "البقعة الحارة22/31", ""),
                            Neighbourhood(277, "البقعة الحارة23 العمران", ""),
                            Neighbourhood(279, "البقعة الحارة24 المودودى", ""),
                            Neighbourhood(281, "الامير الحارة26", ""),
                            Neighbourhood(283, "الامير الحارة27", ""),
                            Neighbourhood(285, "الامير الحارة28", ""),
                            Neighbourhood(287, "الامير الحارة29", ""),
                            Neighbourhood(290, "الامير الحارة3", ""),
                            Neighbourhood(292, "الامير الحارة30", ""),
                            Neighbourhood(293, "البقعة الحارة32القليعة", ""),
                            Neighbourhood(294, "البقعة الحارة33 الجابرية", ""),
                            Neighbourhood(295, "الامير الحارة34 جنوب", ""),
                            Neighbourhood(296, "الامير الحارة34 شمال", ""),
                            Neighbourhood(297, "الامير الحارة35", ""),
                            Neighbourhood(298, "البقعة الحارة36 الكوفة", ""),
                            Neighbourhood(299, "البقعة الحارة37 الدوحة", ""),
                            Neighbourhood(300, "البقعة الحارة38 دار الهجرة", ""),
                            Neighbourhood(301, "السلام الحارة39 العامرية", ""),
                            Neighbourhood(302, "الامير الحارة4", ""),
                            Neighbourhood(304, "البقعة الحارة40 الصفوة", ""),
                            Neighbourhood(305, "البقعة الحارة40 المصطفى", ""),
                            Neighbourhood(306, "البقعة الحارة41/دار الارقم", ""),
                            Neighbourhood(307, "البقعة الحارة42 الوفاق", ""),
                            Neighbourhood(308, "البقعة الحارة43الوحدة", ""),
                            Neighbourhood(309, "السلام الحارة44 العامرية", ""),
                            Neighbourhood(310, "السلام الحارة45", ""),
                            Neighbourhood(311, "البقعة الحارة46 الكوثر", ""),
                            Neighbourhood(312, "الامير الحارة5", ""),
                            Neighbourhood(316, "البقعة الحارة51ود البشير", ""),
                            Neighbourhood(317, "البقعة الحارة52ودالبشيرالصالحين", ""),
                            Neighbourhood(320, "البقعة الحارة6 جنوب القادسية", ""),
                            Neighbourhood(321, "الامير الحارة6 شمال", ""),
                            Neighbourhood(324, "البقعة الحارة7 الصفاء", ""),
                            Neighbourhood(325, "الامير الحارة7 شمال", ""),
                            Neighbourhood(327, "البقعة الحارة8 السبيل", ""),
                            Neighbourhood(328, "البقعة الحارة8 بن عمر", ""),
                            Neighbourhood(330, "البقعة الحارة9 الهدى", ""),
                            Neighbourhood(331, "الحارة9 بن الوليد", ""),
                            Neighbourhood(345, "الحسيناب", ""),
                            Neighbourhood(429, "الرتيلاب", ""),
                            Neighbourhood(431, "الرضوان", ""),
                            Neighbourhood(448, "الساجراب", ""),
                            Neighbourhood(467, "السريحة 20", ""),
                            Neighbourhood(494, "السمرة ود حامد", ""),
                            Neighbourhood(506, "الشداهين", ""),
                            Neighbourhood(580, "العبدلاب", ""),
                            Neighbourhood(717, "الكوارين", ""),
                            Neighbourhood(722, "الكير", ""),
                            Neighbourhood(725, "الماكماب", ""),
                            Neighbourhood(757, "المنارة الجمعاب", ""),
                            Neighbourhood(758, "المنارة شرق", ""),
                            Neighbourhood(759, "المنارة غرب", ""),
                            Neighbourhood(765, "المنوراب", ""),
                            Neighbourhood(770, "المهيداب", ""),
                            Neighbourhood(833, "ام جول", ""),
                            Neighbourhood(834, "ام جولة", ""),
                            Neighbourhood(842, "ام شجرة", ""),
                            Neighbourhood(864, "ام كليوات", ""),
                            Neighbourhood(880, "اولاد ابوشنب", ""),
                            Neighbourhood(883, "اولاد الخير", ""),
                            Neighbourhood(886, "اولاد حامد", ""),
                            Neighbourhood(894, "بانت", ""),
                            Neighbourhood(915, "بير القالباب", ""),
                            Neighbourhood(916, "بير الهوا", ""),
                            Neighbourhood(917, "بير حماد", ""),
                            Neighbourhood(918, "بير رفاي", ""),
                            Neighbourhood(932, "جرقونا", ""),
                            Neighbourhood(933, "جعيرين", ""),
                            Neighbourhood(934, "حاجز ام سيالة", ""),
                            Neighbourhood(1004, "سوق ابوزيد", ""),
                            Neighbourhood(1007, "سوق ليبيا", ""),
                            Neighbourhood(1037, "عد القدير", ""),
                            Neighbourhood(1051, "عشوائي بين 48، 49", ""),
                            Neighbourhood(1069, "قرية ابوبكر الصديق", ""),
                            Neighbourhood(1070, "قرية السامراب", ""),
                            Neighbourhood(1071, "قرية العزبة", ""),
                            Neighbourhood(1072, "قرية الفطيماب", ""),
                            Neighbourhood(1073, "قرية القدير", ""),
                            Neighbourhood(1074, "قرية القسمةالهواوير", ""),
                            Neighbourhood(1075, "قرية صفيرة", ""),
                            Neighbourhood(1076, "قرية نيفاشا", ""),
                            Neighbourhood(1114, "مدينة النصر", ""),
                            Neighbourhood(1118, "السلام مربع1", ""),
                            Neighbourhood(1120, "السلام مربع10", ""),
                            Neighbourhood(1122, "السلام مربع11", ""),
                            Neighbourhood(1124, "السلام مربع12", ""),
                            Neighbourhood(1126, "السلام مربع13 حي الرباط", ""),
                            Neighbourhood(1128, "السلام مربع14", ""),
                            Neighbourhood(1130, "السلام مربع15 الزهراء", ""),
                            Neighbourhood(1132, "السلام مربع16 ابو عبيدة بن الجراح", ""),
                            Neighbourhood(1134, "السلام مربع17 الاندلس", ""),
                            Neighbourhood(1136, "السلام مربع18", ""),
                            Neighbourhood(1138, "السلام مربع19", ""),
                            Neighbourhood(1139, "السلام مربع2", ""),
                            Neighbourhood(1145, "السلام مربع20 دار السلام جنوب", ""),
                            Neighbourhood(1147, "السلام مربع21", ""),
                            Neighbourhood(1149, "السلام مربع22 القادسية", ""),
                            Neighbourhood(1151, "السلام مربع23", ""),
                            Neighbourhood(1153, "السلام مربع24", ""),
                            Neighbourhood(1156, "السلام مربع25", ""),
                            Neighbourhood(1158, "السلام مربع26 الصفا", ""),
                            Neighbourhood(1160, "السلام مربع27", ""),
                            Neighbourhood(1162, "السلام مربع28", ""),
                            Neighbourhood(1164, "السلام مربع29", ""),
                            Neighbourhood(1167, "السلام مربع3", ""),
                            Neighbourhood(1168, "السلام مربع30", ""),
                            Neighbourhood(1169, "السلام مربع31", ""),
                            Neighbourhood(1170, "السلام مربع32", ""),
                            Neighbourhood(1171, "السلام مربع33", ""),
                            Neighbourhood(1173, "السلام مربع34", ""),
                            Neighbourhood(1174, "السلام مربع35", ""),
                            Neighbourhood(1175, "السلام مربع36", ""),
                            Neighbourhood(1177, "السلام مربع37", ""),
                            Neighbourhood(1178, "السلام مربع39", ""),
                            Neighbourhood(1180, "السلام مربع4", ""),
                            Neighbourhood(1184, "السلام مربع40", ""),
                            Neighbourhood(1185, "السلام مربع41", ""),
                            Neighbourhood(1186, "السلام مربع42", ""),
                            Neighbourhood(1188, "السلام مربع43", ""),
                            Neighbourhood(1190, "السلام مربع44", ""),
                            Neighbourhood(1192, "السلام مربع45", ""),
                            Neighbourhood(1194, "السلام مربع46", ""),
                            Neighbourhood(1196, "السلام مربع47", ""),
                            Neighbourhood(1198, "السلام مربع48", ""),
                            Neighbourhood(1200, "السلام مربع49", ""),
                            Neighbourhood(1202, "السلام مربع5", ""),
                            Neighbourhood(1204, "السلام مربع50", ""),
                            Neighbourhood(1209, "السلام مربع6", ""),
                            Neighbourhood(1212, "السلام مربع7", ""),
                            Neighbourhood(1214, "السلام مربع8", ""),
                            Neighbourhood(1216, "السلام مربع9", ""),
                            Neighbourhood(1234, "ود البشير51السريحة", "")
                    ))
            )),
            State(2, "النيل الازرق", "", arrayListOf(
                    District(8, "النيل الازرق", "", arrayListOf(
                            Neighbourhood(1269, "النيل الازرق", "")
                    ))
            )),
            State(3, "النيل الابيض", "", arrayListOf(
                    District(9, "النيل الابيض", "", arrayListOf(
                            Neighbourhood(1270, "النيل الابيض", "")
                    ))
            )),
            State(4, "نهر النيل", "", arrayListOf(
                    District(10, "نهر النيل", "", arrayListOf(
                            Neighbourhood(1271, "نهر النيل", "")
                    ))
            )),
            State(5, "القضارف", "", arrayListOf(
                    District(11, "القضارف", "", arrayListOf(
                            Neighbourhood(1272, "القضارف", "")
                    ))
            )),
            State(6, "كسلا", "", arrayListOf(
                    District(12, "كسلا", "", arrayListOf(
                            Neighbourhood(1273, "كسلا", "")
                    ))
            )),
            State(7, "سنار", "", arrayListOf(
                    District(13, "سنار", "", arrayListOf(
                            Neighbourhood(1274, "سنار", "")
                    ))
            )),
            State(8, "البحر الاحمر", "", arrayListOf(
                    District(14, "البحر الاحمر", "", arrayListOf(
                            Neighbourhood(1275, "البحر الاحمر", "")
                    ))
            )),
            State(9, "الشمالية", "", arrayListOf(
                    District(15, "الشمالية", "", arrayListOf(
                            Neighbourhood(1276, "الشمالية", "")
                    ))
            )),
            State(10, "شمال كردفان", "", arrayListOf(
                    District(16, "شمال كردفان", "", arrayListOf(
                            Neighbourhood(1277, "شمال كردفان", "")
                    ))
            )),
            State(11, "جنوب كردفان", "", arrayListOf(
                    District(17, "جنوب كردفان", "", arrayListOf(
                            Neighbourhood(1278, "جنوب كردفان", "")
                    ))
            )),
            State(12, "غرب دارفور", "", arrayListOf(
                    District(18, "غرب دارفور", "", arrayListOf(
                            Neighbourhood(1279, "غرب دارفور", "")
                    ))
            )),
            State(13, "وسط دارفور", "", arrayListOf(
                    District(19, "وسط دارفور", "", arrayListOf(
                            Neighbourhood(1280, "وسط دارفور", "")
                    ))
            )),
            State(14, "شمال دارفور", "", arrayListOf(
                    District(20, "شمال دارفور", "", arrayListOf(
                            Neighbourhood(1281, "شمال دارفور", "")
                    ))
            )),
            State(15, "شرق دارفور", "", arrayListOf(
                    District(21, "شرق دارفور", "", arrayListOf(
                            Neighbourhood(1282, "شرق دارفور", "")
                    ))
            )),
            State(16, "جنوب دارفور", "", arrayListOf(
                    District(22, "جنوب دارفور", "", arrayListOf(
                            Neighbourhood(1283, "جنوب دارفور", "")
                    ))
            ))
    )

}